FınalProjectBeginning/Models/Evaluation.cs
namespace FınalProjectBeginning.Models
{
    public class Evaluation
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public bool Like {  get; set; }

        public string? CetUserId { get; set; }
        public virtual CetUser? CetUser { get; set; }

        public int? EventId { get; set; }
        public virtual Event? Event { get; set; }
    }
}

FınalProjectBeginning/Models/Evaluations.cs
namespace FınalProjectBeginning.Models
{
    public class Evaluations
    {
        public int Id { get; set; }
        public string Yorum { get; set; }
        public bool Like { get; set;}

        public string? CetUserId { get; set; }
        public virtual CetUser? CetUser { get; set; }


        public int EventId { get; set; }
        public virtual Event? Event { get; set; }
    }
}

FınalProjectBeginning/Controllers/EvaluationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectBeginning.Data;
using FınalProjectBeginning.Models;
using Microsoft.SqlServer.Management.XEvent;

namespace FınalProjectBeginning.Controllers
{
    public class EvaluationsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EvaluationsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Evaluations
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Evaluations.Include(e => e.CetUser).Include(e => e.Event);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Evaluations/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await _context.Evaluations
                .Include(e => e.CetUser)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }

            return View(evaluation);
        }

        // GET: Evaluations/Create
        public IActionResult Create(int? eventId)
        {
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id");
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Id",eventId);
            return View();
        }

        // POST: Evaluations/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,Description,CetUserId,EventId")] Evaluation evaluation)
        {

            var CetUser = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            evaluation.CetUserId = CetUser.Id;
            _context.Evaluations.Add(evaluation);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

            //if (ModelState.IsValid)
            //{
            //    _context.Add(evaluation);
            //    await _context.SaveChangesAsync();
            //    return RedirectToAction(nameof(Index));
            //}
            //ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", evaluation.CetUserId);
            //ViewData["EventId"] = new SelectList(_context.Events, "Id", "Id", evaluation.EventId);
            //return View(evaluation);
        }

        // GET: Evaluations/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await _context.Evaluations.FindAsync(id);
            if (evaluation == null)
            {
                return NotFound();
            }
            var userID = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name)?.Id;
            if (evaluation.CetUserId != userID) { return Unauthorized(); }
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", evaluation.CetUserId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Id", evaluation.EventId);
            return View(evaluation);
        }

        // POST: Evaluations/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Title,Description,CetUserId,EventId")] Evaluation evaluation)
        {
            if (id != evaluation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(evaluation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EvaluationExists(evaluation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", evaluation.CetUserId);
            ViewData["EventId"] = new SelectList(_context.Events, "Id", "Id", evaluation.EventId);
            return View(evaluation);
        }

        // GET: Evaluations/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var evaluation = await _context.Evaluations
                .Include(e => e.CetUser)
                .Include(e => e.Event)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (evaluation == null)
            {
                return NotFound();
            }
            var userID = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name)?.Id;
            if (evaluation.CetUserId != userID) { return Unauthorized(); }

            return View(evaluation);
        }

        // POST: Evaluations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var evaluation = await _context.Evaluations.FindAsync(id);
            if (evaluation != null)
            {
                _context.Evaluations.Remove(evaluation);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EvaluationExists(string id)
        {
            return _context.Evaluations.Any(e => e.Id == id);
        }
    }
}

FınalProjectBeginning/Views/Evaluations/Create.cshtml
@model FınalProjectBeginning.Models.Evaluation

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Evaluation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="CetUserId" class="control-label"></label>
                <select asp-for="CetUserId" class ="form-control" asp-items="ViewBag.CetUserId"></select>
            </div> *@
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                <select asp-for="EventId" class ="form-control" asp-items="ViewBag.EventId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FınalProjectBeginning/Views/Evaluations/Delete.cshtml
@model FınalProjectBeginning.Models.Evaluation

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CetUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CetUser.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Event.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FınalProjectBeginning/Views/Evaluations/Details.cshtml
@model FınalProjectBeginning.Models.Evaluation

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Evaluation</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CetUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CetUser.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Event)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Event.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
    <a asp-controller="Evaluations" asp-action="Create"><btn>Add Eva</btn></a>
    <a asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</div>

FınalProjectBeginning/Views/Evaluations/Edit.cshtml
@model FınalProjectBeginning.Models.Evaluation

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Evaluation</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CetUserId" class="control-label"></label>
                <select asp-for="CetUserId" class="form-control" asp-items="ViewBag.CetUserId"></select>
                <span asp-validation-for="CetUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EventId" class="control-label"></label>
                <select asp-for="EventId" class="form-control" asp-items="ViewBag.EventId"></select>
                <span asp-validation-for="EventId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FınalProjectBeginning/Views/Evaluations/Index.cshtml
@model IEnumerable<FınalProjectBeginning.Models.Evaluation>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<CetUser> SignInManager
@inject UserManager<CetUser> UserManager
@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table text-black">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CetUser)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Event)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CetUser.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Event.Title)
            </td>
            <td>
                @if (SignInManager.IsSignedIn(User) && User.IsInRole("Restoran") && item.CetUserId == UserManager.GetUserId(User))
                {
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                }
                else
                {
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>




<section class="client_section layout_padding-bottom">
    <div class="container">
        <div class="heading_container heading_center psudo_white_primary mb_45">
            <h2>
                What Says Our Customers
            </h2>
        </div>
        <div class="carousel-wrap row ">
            <div class="owl-carousel client_owl-carousel owl-loaded owl-drag">


                <div class="owl-stage-outer">
                    <div class="owl-stage" style="transform: translate3d(-1440px, 0px, 0px); transition: all 0.25s ease 0s; width: 2880px;">
                        @foreach (var item in Model)
                        {
                            <div class="owl-item cloned" style="width: 480px;">
                                <div class="item">
                                    <div class="box">
                                        <div class="detail-box">
                                            <p>
                                                @item.Description
                                            </p>
                                            <h6>
                                                @item.CetUser.Name
                                            </h6>
                                            <p>
                                                magna aliqua
                                            </p>
                                        </div>
                                        <div class="img-box">
                                            <img src="~/images/@item.Event.ImageName" alt="" class="box-img">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        
                    </div>
                </div>
                <div class="owl-nav disabled">
                    <button type="button" role="presentation" class="owl-prev"><i class="fa fa-angle-left" aria-hidden="true"></i></button>
                    <button type="button" role="presentation" class="owl-next"><i class="fa fa-angle-right" aria-hidden="true"></i></button>
                </div>
                <div class="owl-dots disabled">
                </div>
            </div>
        </div>
    </div>
</section>