FınalProjectBeginning/Models/Kulsayfasi.cs
namespace FınalProjectBeginning.Models
{
    public class Kulsayfasi
    {
        public int Id { get; set; }
        public string ImageName { get; set; }
        public string Description { get; set; }
        public bool IsFollowedByCurrentUser { get; set; }

        public string? CetUserId { get; set; }
        public virtual CetUser? CetUser { get; set; }

    }
}

FınalProjectBeginning/Controllers/KulsayfasisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectBeginning.Data;
using FınalProjectBeginning.Models;
using Microsoft.SqlServer.Management.XEvent;
using Microsoft.AspNetCore.Identity;
using FınalProjectBeginning.Migrations;
using System.Security.Claims;
using Microsoft.SqlServer.Management.Smo;

namespace FınalProjectBeginning.Controllers
{
    public class KulsayfasisController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<CetUser> _userManager;



        public KulsayfasisController(ApplicationDbContext context, UserManager<CetUser> userManager)
        {
            _context = context;

            _userManager = userManager;
        }

        // GET: Posts

        public async Task<IActionResult> Index()
        {
            
            var currentUserId = User.Identity.Name;

            var applicationDbContext = await _context.Kulsayfasis
                .Include(k => k.CetUser)
                .ThenInclude(a=>a.Kulsayfasis)
                .Select(k => new Kulsayfasi
                {
                    
                    Id = k.Id,
                    Description = k.Description,
                    CetUser = k.CetUser,
                    IsFollowedByCurrentUser = _context.Takip_Takipcis
                        .Any(tt => tt.TakipEdenUserId == currentUserId && tt.TakipEdilenKisiId == k.CetUser.Id)
                })
                .ToListAsync();

            


            return View(applicationDbContext);
        }


        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kulsayfasi = await _context.Kulsayfasis
                .Include(p => p.CetUser)
                .ThenInclude(u => u.Posts)
                .Include(k => k.CetUser)
                .ThenInclude(c => c.TakipEdilenKisis)
                .Include(k => k.CetUser)
                .ThenInclude(c => c.TakipEdenUsers)

                .FirstOrDefaultAsync(m => m.Id == id);
            if (kulsayfasi == null)
            {
                return NotFound();
            }

            return View(kulsayfasi);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id");
            
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile kulsayImage, [Bind("Id,Description,CetUserId")] Kulsayfasi kulsayfasi)
        {
            //var existingData = _context.Kulsayfasis.FirstOrDefault(k => k.CetUserId == kulsayfasi.CetUserId);

            
            //if (existingData != null)
            //{
            //    // Kullanıcı zaten bir veri oluşturmuş, yeni bir oluşturma işlemine izin verme
            //    //TempData["Message"] = "You have already created a data entry.";
            //    //return RedirectToAction(nameof(Index));

            //    return Unauthorized();
            //}

            var filename = kulsayImage.FileName;
            var extension = Path.GetExtension(filename);
            var newfilename = Guid.NewGuid().ToString().ToLower().Replace("-", "") + extension;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", newfilename);

            using (var stream = new FileStream(path, FileMode.CreateNew))
            {
                await kulsayImage.CopyToAsync(stream);
            }
            kulsayfasi.ImageName = newfilename;
            _context.Add(kulsayfasi);

            var CetUser = _context.Users.FirstOrDefault(u=>u.UserName == User.Identity.Name);
            kulsayfasi.CetUserId = CetUser.Id;
            _context.Kulsayfasis.Add(kulsayfasi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));


        }

        // GET: Posts/Edit/5
        [HttpGet]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Kulsayfasis.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", post.CetUserId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Description,CetUserId")] Kulsayfasi kulsayfasi)
        {
            if (id != kulsayfasi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kulsayfasi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KulsayfasiExists(kulsayfasi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", kulsayfasi.CetUserId);
            return View(kulsayfasi);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kulsayfasi = await _context.Kulsayfasis
                .Include(p => p.CetUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kulsayfasi == null)
            {
                return NotFound();
            }

            return View(kulsayfasi);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kulsayfasi = await _context.Kulsayfasis.FindAsync(id);
            if (kulsayfasi != null)
            {
                _context.Kulsayfasis.Remove(kulsayfasi);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> MyPosts()
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return Challenge();
            }

            var cetUser = await _context.CetUsers
                .Include(c => c.Posts) // Posts koleksiyonunu dahil edin
                .FirstOrDefaultAsync(c => c.Id == user.Id); // IdentityUserId'nin user.Id ile eşleştiğinden emin olun

            if (cetUser == null)
            {
                return NotFound();
            }

            var posts = cetUser.Posts; // Kullanıcının postlarını alın
            return View(posts);
        }



        public IActionResult Search(string searchString)
        {
            var users = from u in _context.Kulsayfasis.Include(k => k.CetUser)
                        select u;

            if (!String.IsNullOrEmpty(searchString))
            {
                //users = users.Where(s => s.CetUser.Name.Contains(searchString) || s.CetUser.Surname.Contains(searchString));

                // Kullanıcı adı veya soyadı arama metni ile başlıyorsa
                users = users.Where(s => s.CetUser.Name.StartsWith(searchString) || s.CetUser.Surname.StartsWith(searchString));
            }

            return View(users.ToList());
        }















        private bool KulsayfasiExists(int id)

    {
        return _context.Kulsayfasis.Any(e => e.Id == id);
    }















        //[HttpPost]
        //public IActionResult FollowUser([FromBody] string userId) 
        //{
        //    var currentUser = _context.Users.FirstOrDefault(u => u.Id == User.Identity.Name);
        //    var followedUser = _context.Users.FirstOrDefault(u => u.Id == userId);

        //    if (currentUser != null && followedUser != null)
        //    {
        //        var existingRelationship = _context.Takip_Takipcis.FirstOrDefault(r => r.TakipEdenUserId == currentUser.Id && r.TakipEdilenKisiId == followedUser.Id);

        //        if (existingRelationship != null)
        //        {
        //            _context.Takip_Takipcis.Remove(existingRelationship);
        //            _context.SaveChanges();
        //            return Json("unfollowed");
        //        }
        //        else
        //        {
        //            _context.Takip_Takipcis.Add(new Takip_Takipci { TakipEdenUserId = currentUser.Id, TakipEdilenKisiId = followedUser.Id });
        //            _context.SaveChanges();
        //            return Json("followed");
        //        }
        //    }

        //    return Json("error");
        //}



        [HttpPost]
        public IActionResult FollowUser(string userId)
        {
            var currentUserId = User.FindFirstValue(ClaimTypes.NameIdentifier);

            var currentUserExists = _context.CetUsers.Any(u => u.Id == currentUserId);

FınalProjectBeginning/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FinalProjectBeginning.Data;
using FınalProjectBeginning.Models;
using Microsoft.SqlServer.Management.XEvent;

namespace FınalProjectBeginning.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PostsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Posts.Include(p => p.CetUser);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.CetUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        // GET: Posts/Create
        public IActionResult Create()
        {
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id");
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormFile postImage,[Bind("Id,Title,Description,CetUserId")] Post post)
        {
            var filename = postImage.FileName;
            var extension = Path.GetExtension(filename);
            var newfilename = Guid.NewGuid().ToString().ToLower().Replace("-", "") + extension;

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\images", newfilename);

            using (var stream = new FileStream(path, FileMode.CreateNew))
            {
                await postImage.CopyToAsync(stream);
            }
            post.ImageName = newfilename;
            _context.Add(post);

            var CetUser = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name);
            post.CetUserId = CetUser.Id;
            _context.Posts.Add(post);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        // GET: Posts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts.FindAsync(id);
            if (post == null)
            {
                return NotFound();
            }
            var userID = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name)?.Id;
            if (post.CetUserId != userID) { return Unauthorized(); }

            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", post.CetUserId);
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,CetUserId")] Post post)
        {
            if (id != post.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(post);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PostExists(post.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CetUserId"] = new SelectList(_context.CetUsers, "Id", "Id", post.CetUserId);
            return View(post);
        }

        // GET: Posts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Posts
                .Include(p => p.CetUser)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (post == null)
            {
                return NotFound();
            }
            var userID = _context.Users.FirstOrDefault(u => u.UserName == User.Identity.Name)?.Id;
            if (post.CetUserId != userID) { return Unauthorized(); }

            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PostExists(int id)
        {
            return _context.Posts.Any(e => e.Id == id);
        }
        
    }
}

FınalProjectBeginning/Views/Kulsayfasis/Create.cshtml
@model FınalProjectBeginning.Models.Kulsayfasi




@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            @* <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            @* <div class="form-group">
                <label asp-for="CetUserId" class="control-label"></label>
                <select asp-for="CetUserId" class ="form-control" asp-items="ViewBag.CetUserId"></select>
            </div> *@
            <div class="form-group">
                <label class="control-label">Image</label>
                <input type="file" name="kulsayImage" id="kulsayImage" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FınalProjectBeginning/Views/Kulsayfasis/Delete.cshtml
@model FınalProjectBeginning.Models.Kulsayfasi

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Post</h4>
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CetUser)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CetUser.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

FınalProjectBeginning/Views/Kulsayfasis/Details.cshtml
@model FınalProjectBeginning.Models.Kulsayfasi


<main style="margin-top: 40px;">
    <div class="container">
        <div class="row m-b-r m-t-3">
            <div class="col-md-2 offset-md-1">
                <img src="~/images/@Model.ImageName" alt="" class="img-circle img-fluid">
            </div>
            <div class="col-md-9 p-t-2">
                <h2 class="h2-responsive">@Model.CetUser.Name <button type="button" class="btn btn-info-outline waves-effect text-white">Follow</button></h2>
                <p>@User.Identity.Name @ViewBag.Name</p>

                <ul class="flex-menu">
                    <li><strong>@Model.CetUser.Posts.Count() </strong> posts</li>
                    <li><strong>@Model.CetUser.TakipEdenUsers.Count()</strong> followers</li>
                    <li><strong>@Model.CetUser.TakipEdilenKisis.Count()</strong> following</li>
                </ul>
            </div>
        </div>
        <section class="food_section layout_padding">
            <div class="container">

                <div class="filters-content">
                    <div class="row grid">

                        @foreach (var post in Model.CetUser.Posts)
                        {
                            <div class="col-sm-6 col-lg-4 all pizza">
                                <div class="box">
                                    <div>
                                        @* <div class="img-box">
                                    <a asp-controller="Posts" asp-action="Details" asp-route-id="@item.Id">
                                    <img src="images/@item.ImageName" alt="" >
                                    </a> *@
                                        
                                        <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.Id">
                                            <img src="~/images/@post.ImageName" alt="" width="100%" height="250px" >
                                        </a>
                                        
                                    </div>
                                       
                                    </div>
                                </div>


                        }

                    </div>
                </div>
            </div>
        </section>
    </div>
</main>

FınalProjectBeginning/Views/Kulsayfasis/Edit.cshtml
@model FınalProjectBeginning.Models.Kulsayfasi

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Post</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            @* <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CetUserId" class="control-label"></label>
                <select asp-for="CetUserId" class="form-control" asp-items="ViewBag.CetUserId"></select>
                <span asp-validation-for="CetUserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

FınalProjectBeginning/Views/Kulsayfasis/Index.cshtml
@model IEnumerable<FınalProjectBeginning.Models.Kulsayfasi>
@using Microsoft.AspNetCore.Identity
@using System.Security.Claims
@inject SignInManager<CetUser> SignInManager
@inject UserManager<CetUser> UserManager
@{
    ViewData["Title"] = "Index";
}
@{
    var kulsayfasiId = ViewBag.KulsayfasiId;
}
@section Styles {
    <style class="sub_page">
        body {
           
            /* background-color: #222831; */
            
        }
    </style>
}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menu</title>
    <style>
        .food_section h2,
        .food_section h5,
        .food_section h4,
        .food_section p,
        .food_section btn {
            color: #fff;
        }
    </style>
</head>

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table text-black">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Description)</th>
            <th>@Html.DisplayNameFor(model => model.CetUser)</th>
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Description)</td>
                <td>@Html.DisplayFor(modelItem => item.CetUser.Id)</td>
                <td>
                    @if (User.Identity.IsAuthenticated && item.CetUser.Id != User.Identity.Name)
                    {
                        if (User.Identity.Name == item.CetUser.Name)
                        {

                        }
                        else
                        {
                            var isFollowed = item.IsFollowedByCurrentUser; // Adjust based on your model
                            @* <button id="followButton_@item.CetUser.Id" onclick="toggleFollow('@item.CetUser.Id', this)">
                                @(isFollowed ? "Takip Ediliyor" : "Takip Et")
                            </button> *@

                            <button id="followButton_@item.CetUser.Id" onclick="toggleFollow('@item.CetUser.Id', this)">
                                <span id="followButtonText_@item.CetUser.Id">@((isFollowed ? "Takip Ediliyor" : "Takip Et"))</span>
                            </button>
                        } 
                    }
                </td>
                <td>
                    @if (SignInManager.IsSignedIn(User)  && item.CetUser.Id == UserManager.GetUserId(User))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> 
                        <a asp-action="Details" asp-route-id="@item.Id">Details</a> 
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                    else
                    {
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@* CSRF token'ı almak için form oluşturuyoruz *@
<form id="csrf-form" style="display:none;">
    @Html.AntiForgeryToken()
</form>

<section class="food_section layout_padding">
    <div class="container">
        
        <div class="filters-content">
            <div class="row grid">
                @foreach (var item in Model)
                {

                    <div class="col-sm-6 col-lg-4 all pizza">
                        <div class="box">
                            <div>
                                <div class="img-box">
                                    <a asp-controller="Kulsayfasis" asp-action="Details" asp-route-id="@item.Id">
                                        <img src="images/@item.ImageName" alt="">
                                        <p>@item.ImageName</p>
                                    </a>
                                </div>
                                <div class="detail-box">
                                    <h5>
                                        @item.CetUser
                                    </h5>
                                    <h4>
                                        @item.CetUser.Name
                                    </h4>
                                    <p>
                                        @item.Description
                                    </p>
                                    <div>

                                        
                                        <button >
                                           Takip et
                                        </button>
                                        


                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</section>


@section Scripts {
    <script>
        function getAntiForgeryToken() {
            return $('input[name="__RequestVerificationToken"]').val();
        }

        function toggleFollow(userId, button) {
            var isFollowing = button.innerText === "Takip Ediliyor";
            var url = isFollowing ? '/Kulsayfasis/UnfollowUser' : '/Kulsayfasis/FollowUser';

            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    userId: userId,
                    __RequestVerificationToken: getAntiForgeryToken()
                },
                success: function (data) {
                    if (data === "followed") {
                        button.innerText = "Takip Ediliyor";
                    } else if (data === "unfollowed") {
                        button.innerText = "Takip Et";
                    }
                }
            });
        }

        // Sayfa yüklendiğinde, her butonun takip durumunu kontrol etmek için
        $(document).ready(function () {
            $('[id^=followButton_]').each(function () {
                var userId = this.id.split('_')[1];
                var button = this;
                toggleFollow(userId, button); // Takip durumunu kontrol et
            });
        });

    </script>
}

FınalProjectBeginning/Views/Kulsayfasis/MYposts.cshtml
@model List<FınalProjectBeginning.Models.Post>

<h1>My Posts</h1>

@if (!Model.Any())
{
    <p>You have no posts.</p>
}
else
{
    <ul>
        @foreach (var post in Model)
        {
            <li>
                <a asp-controller="Posts" asp-action="Details" asp-route-id="@post.Id">
                    <img src="~/images/@post.ImageName" alt="Post Image" style="width:100px;height:auto;" />
                    @post.Title
                </a>
            </li>
        }
    </ul>
}

FınalProjectBeginning/Views/Kulsayfasis/Search.cshtml
@model IEnumerable<FınalProjectBeginning.Models.Kulsayfasi>

@{
    ViewData["Title"] = "User Search";
}

<h1>User Search</h1>

<form asp-action="Search" method="get">
    <p>
        Search by name: <input type="text" name="searchString" />
        <input type="submit" value="Search" />
    </p>
</form>

<table class="table text-black">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.CetUser.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CetUser.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CetUser.Email)                
            </th>
            <th>

            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.CetUser.Name)
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CetUser.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CetUser.Email)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                </td>
            </tr>
        }
    </tbody>
</table>